// <auto-generated />
namespace CRMStart.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class exterminategemini : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(exterminategemini));
        
        string IMigrationMetadata.Id
        {
            get { return "201602191434545_exterminate-gemini"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
